<?php


define('ROOT', dirname(__DIR__, 2).DIRECTORY_SEPARATOR);
define('APPLICATION', ROOT.'application'.DIRECTORY_SEPARATOR);
define('CORE', APPLICATION.'core'.DIRECTORY_SEPARATOR);
define('MODELS', APPLICATION.'models'.DIRECTORY_SEPARATOR);
define('VIEWS', APPLICATION.'views'.DIRECTORY_SEPARATOR);
define('CONTROLLERS', APPLICATION.'controllers'.DIRECTORY_SEPARATOR);
